### ISSUE TITLE
AttributeError: 'KaldiRecognizer' object has no attribute '_handle'

### ISSUE THREAD

**Issue by Tortoise17** [alphacep/vosk#11]
your new release has this bug. ! please check if maybe I am on mistake.

**Comment by Tortoise17** [comment]
```
rec = KaldiRecognizer(model, spk_model, wf.getframerate())
  File "/home/anaconda3/envs/t/lib/python3.7/site-packages/vosk/__init__.py", line 52, in __init__
    raise TypeError("Unknown arguments")
TypeError: Unknown arguments
Exception ignored in: <function KaldiRecognizer.__del__ at 0x7f1a765bc3b0>
Traceback (most recent call last):
  File "/home/anaconda3/envs/t/lib/python3.7/site-packages/vosk/__init__.py", line 55, in __del__
    _c.vosk_recognizer_free(self._handle)
AttributeError: 'KaldiRecognizer' object has no attribute '_handle'
```

**Comment by nshmyrev** [comment]
Try the other order of arguments:

`rec = KaldiRecognizer(model, wf.getframerate(), spk_model)`
